version: '3'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '${DB_HOST:-127.0.0.1}:${DB_PORT:-5432}:5432'
    command: ['postgres', '-cshared_preload_libraries=pg_stat_statements']
    environment:
      POSTGRES_USER: claim-backend
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: claim-backend
    volumes:
      - ./postgres:/var/lib/postgresql/data
