version: '3'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '${DB_HOST:-127.0.0.1}:${DB_PORT:-5432}:5432'
    command: ['postgres', '-cshared_preload_libraries=pg_stat_statements']
    environment:
      POSTGRES_USER: claim-backend
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: claim-backend
    volumes:
      - ./postgres:/var/lib/postgresql/data
    secrets:
      - db_password

secrets:
  db_password:
    file: ${DB_PASSWORD_PATH:-db_password.txt}
