name: 'PR'
on:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install yarn
        run: npm install --global yarn
      - name: Install dependencies
        shell: bash
        run: yarn --prefer-offline
      - name: Build
        shell: bash
        run: yarn build
      - run: yarn format
      - name: Check format
        run: |
          if [ -z "$(git status --untracked-files=no --porcelain)" ]; then
            echo "All files formatted"
          else
            echo "Running format is required"
            exit 1
          fi
      - run: yarn test
